### PR TITLE
Fix compatibility with laravel/framework#49231

### LINKED ISSUE #81: Declaration of `Umbrellio\Postgres\Schema\Builder::hasView(string $view): bool` must be compatible with `Illuminate\Database\Schema\Builder::hasView($view)`
- Conflicts with https://github.com/laravel/framework/pull/49231

```php
    /**
     * Determine if the given view exists.
     *
     * @param  string  $view
     * @return bool
     */
    public function hasView($view)
    {
        $view = $this->connection->getTablePrefix().$view;

        foreach ($this->getViews() as $value) {
            if (strtolower($view) === strtolower($value['name'])) {
                return true;
            }
        }

        return false;
    }
```

```php
    public function hasView(string $view): bool
    {
        return count($this->connection->selectFromWriteConnection($this->grammar->compileViewExists(), [
            $this->connection->getConfig()['schema'],
            $this->connection->getTablePrefix() . $view,
        ])) > 0;
    }
```

### PR DESCRIPTION
**Pull request by mpyw**
- Fixes #81

### CODE REVIEW

File: src/Schema/Builder.php [hunk 1]
```diff
@@ -28,7 +28,7 @@ public function dropView(string $view): void
         $this->build($blueprint);
     }
 
-    public function hasView(string $view): bool
+    public function hasView($view): bool
     {
```
Comment (mpyw) [inline src/Schema/Builder.php:32]: Argument types must NOT be narrowed, whereas return types can be narrowed.

**Comment by mpyw** [comment]
Hi, Umbrellio Teams

@tycooon
@nulldef
@scatmanoleg
@eugeneyak
@AnotherRegularDude
@VMashanov
@wildkain
@pvsaintpe
@basherru
@nesaulov
@0exp
@lazeevv
@qem19

Please review the pull-request, this is such an important fix.
Currently every Laravel user cannot upgrade the version due to the issue.

I'll appreciate for your help.

**Review by pvsaintpe — APPROVED** [review]
